//@ui5-bundle BridgeManagementV2/operations/restrictions/Component-preload.js
sap.ui.predefine("BridgeManagementV2/operations/restrictions/Component", ["sap/ui/core/UIComponent"],e=>{"use strict";return e.extend("bms.operations.restrictions",{metadata:{manifest:"json"}})});
sap.ui.predefine("BridgeManagementV2/operations/restrictions/controller/Main.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],(e,t)=>{"use strict";const i="/odata/v4/admin/Restrictions?$select=ID,restrictionType,bridgeName,restrictionStatus,grossMassLimit,heightLimit,speedLimit,permitRequired&$filter=active eq true";return e.extend("bms.operations.restrictions.controller.Main",{onInit(){this.getView().setModel(new t({restrictions:[]}),"view");this._allRestrictions=[];this._loadRestrictions()},_loadRestrictions(){fetch(i).then(e=>e.json()).then(e=>{const t=e.value||[];this._allRestrictions=t;this.getView().getModel("view").setProperty("/restrictions",t)}).catch(()=>{this.getView().getModel("view").setProperty("/restrictions",[])})},onSearch(e){const t=(e.getParameter("newValue")||e.getParameter("query")||"").toLowerCase().trim();if(!t){this.getView().getModel("view").setProperty("/restrictions",this._allRestrictions);return}const i=this._allRestrictions.filter(e=>String(e.bridgeName||"").toLowerCase().includes(t));this.getView().getModel("view").setProperty("/restrictions",i)}})});
sap.ui.require.preload({
	"BridgeManagementV2/operations/restrictions/Component-preload.js":function(){
sap.ui.require.preload({});
},
	"BridgeManagementV2/operations/restrictions/i18n/i18n.properties":'appTitle=Restrictions\nappDescription=View and manage bridge load and access restrictions\nappSubTitle=Restriction Management\n',
	"BridgeManagementV2/operations/restrictions/manifest.json":'{"_version":"1.8.0","sap.app":{"id":"BridgeManagementV2.operations.restrictions","type":"application","title":"{{appTitle}}","description":"{{appDescription}}","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"dataSources":{},"crossNavigation":{"inbounds":{"Restrictions-display":{"semanticObject":"Restrictions","action":"display","signature":{"parameters":{},"additionalParameters":"allowed"},"title":"{{appTitle}}","icon":"sap-icon://alert"}}}},"sap.ui5":{"dependencies":{"minUI5Version":"1.120.0","libs":{"sap.m":{},"sap.ui.core":{},"sap.ui.layout":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"}},"rootView":{"viewName":"bms.operations.restrictions.view.Main","type":"XML","async":true,"id":"root"},"contentDensities":{"compact":true,"cozy":true},"flexBundle":false},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.fiori":{"registrationIds":[],"archeType":"analytical"}}',
	"BridgeManagementV2/operations/restrictions/view/Main.view.xml":'<mvc:View\n    controllerName="bms.operations.restrictions.controller.Main"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    displayBlock="true"\n    height="100%"><App id="app"><pages><Page title="{i18n>appTitle}" showHeader="true"><subHeader><Bar><contentMiddle><SearchField\n                                id="restrictionSearch"\n                                placeholder="Search by bridge name"\n                                width="40%"\n                                search=".onSearch"\n                                liveChange=".onSearch"/></contentMiddle></Bar></subHeader><content><Table\n                        id="restrictionsTable"\n                        items="{view>/restrictions}"\n                        growing="true"\n                        growingThreshold="50"\n                        noDataText="No active restrictions found"><columns><Column><Text text="Restriction Type"/></Column><Column><Text text="Bridge Name"/></Column><Column><Text text="Status"/></Column><Column hAlign="End"><Text text="Gross Mass (t)"/></Column><Column hAlign="End"><Text text="Height (m)"/></Column><Column hAlign="End"><Text text="Speed (km/h)"/></Column><Column hAlign="Center"><Text text="Permit Required"/></Column></columns><items><ColumnListItem><cells><Text text="{view>restrictionType}"/><Text text="{view>bridgeName}"/><Text text="{view>restrictionStatus}"/><Text text="{view>grossMassLimit}"/><Text text="{view>heightLimit}"/><Text text="{view>speedLimit}"/><Text text="{= ${view>permitRequired} ? \'Yes\' : \'No\' }"/></cells></ColumnListItem></items></Table></content></Page></pages></App></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
