//@ui5-bundle BridgeManagementV2/operations/bridges/Component-preload.js
sap.ui.predefine("BridgeManagementV2/operations/bridges/Component", ["sap/ui/core/UIComponent"],e=>{"use strict";return e.extend("bms.operations.bridges",{metadata:{manifest:"json"}})});
sap.ui.predefine("BridgeManagementV2/operations/bridges/controller/Main.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/ui/model/Filter","sap/ui/model/FilterOperator"],(e,t,i,r)=>{"use strict";return e.extend("bms.operations.bridges.controller.Main",{onInit(){this.getView().setModel(new t({bridges:[]}),"view");this._allBridges=[];this._loadBridges()},_loadBridges(){fetch("/map/api/bridges").then(e=>e.json()).then(e=>{const t=Array.isArray(e)?e:e.bridges||e.value||[];this._allBridges=t;this.getView().getModel("view").setProperty("/bridges",t)}).catch(()=>{this.getView().getModel("view").setProperty("/bridges",[])})},onSearch(e){const t=(e.getParameter("newValue")||e.getParameter("query")||"").toLowerCase().trim();if(!t){this.getView().getModel("view").setProperty("/bridges",this._allBridges);return}const i=this._allBridges.filter(e=>String(e.bridgeName||"").toLowerCase().includes(t)||String(e.ID||"").toLowerCase().includes(t));this.getView().getModel("view").setProperty("/bridges",i)},onOpenInMap(e){const t=e.getSource().getBindingContext("view");const i=t.getProperty("ID");sap.m.URLHelper.redirect("#Map-display?bridgeId="+encodeURIComponent(i),false)}})});
sap.ui.require.preload({
	"BridgeManagementV2/operations/bridges/Component-preload.js":function(){
sap.ui.require.preload({});
},
	"BridgeManagementV2/operations/bridges/i18n/i18n.properties":'appTitle=Bridges\nappDescription=Manage bridge assets in the Bridge Management System\nappSubTitle=Bridge Management\n',
	"BridgeManagementV2/operations/bridges/manifest.json":'{"_version":"1.8.0","sap.app":{"id":"BridgeManagementV2.operations.bridges","type":"application","title":"{{appTitle}}","description":"{{appDescription}}","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"dataSources":{},"crossNavigation":{"inbounds":{"Bridges-manage":{"semanticObject":"Bridges","action":"manage","signature":{"parameters":{},"additionalParameters":"allowed"},"title":"{{appTitle}}","icon":"sap-icon://functional-location"}}}},"sap.ui5":{"dependencies":{"minUI5Version":"1.120.0","libs":{"sap.m":{},"sap.ui.core":{},"sap.ui.layout":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"}},"rootView":{"viewName":"bms.operations.bridges.view.Main","type":"XML","async":true,"id":"root"},"contentDensities":{"compact":true,"cozy":true},"flexBundle":false},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.fiori":{"registrationIds":[],"archeType":"analytical"}}',
	"BridgeManagementV2/operations/bridges/view/Main.view.xml":'<mvc:View\n    controllerName="bms.operations.bridges.controller.Main"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    displayBlock="true"\n    height="100%"><App id="app"><pages><Page title="{i18n>appTitle}" showHeader="true"><subHeader><Bar><contentMiddle><SearchField\n                                id="bridgeSearch"\n                                placeholder="Search by name or ID"\n                                width="40%"\n                                search=".onSearch"\n                                liveChange=".onSearch"/></contentMiddle></Bar></subHeader><content><Table\n                        id="bridgesTable"\n                        items="{view>/bridges}"\n                        growing="true"\n                        growingThreshold="50"\n                        noDataText="No bridges found"><columns><Column><Text text="Bridge Name"/></Column><Column><Text text="ID"/></Column><Column><Text text="State"/></Column><Column><Text text="Posting Status"/></Column><Column><Text text="Condition Rating"/></Column><Column><Text text="Structure Type"/></Column><Column hAlign="End"><Text text=""/></Column></columns><items><ColumnListItem><cells><Text text="{view>bridgeName}"/><Text text="{view>ID}"/><Text text="{view>state}"/><Text text="{view>postingStatus}"/><Text text="{view>conditionRating}"/><Text text="{view>structureType}"/><Button\n                                        icon="sap-icon://map"\n                                        tooltip="Open in Map"\n                                        type="Transparent"\n                                        press=".onOpenInMap"/></cells></ColumnListItem></items></Table></content></Page></pages></App></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
